# 4.5 Cigarette smokers

## chanSem.go

Literal interpretation, with agents, pushers, and smokers just started from
function literals.

----
$ go run -race chanSem.go
2018/02/04 19:28:24 agent provides tobacco and paper
2018/02/04 19:28:24 smoker with matches makes cigarette
2018/02/04 19:28:24 smoker with matches smokes
2018/02/04 19:28:24 agent provides paper and a match
2018/02/04 19:28:24 smoker with tobacco makes cigarette
2018/02/04 19:28:24 smoker with tobacco smokes
2018/02/04 19:28:24 agent provides tobacco and a match
2018/02/04 19:28:24 smoker with paper makes cigarette
2018/02/04 19:28:24 agent provides tobacco and paper
2018/02/04 19:28:24 smoker with paper smokes
2018/02/04 19:28:24 smoker with matches makes cigarette
2018/02/04 19:28:24 smoker with matches smokes
2018/02/04 19:28:24 agent provides paper and a match
2018/02/04 19:28:24 smoker with tobacco makes cigarette
2018/02/04 19:28:24 smoker with tobacco smokes
2018/02/04 19:28:24 agent provides tobacco and a match
2018/02/04 19:28:24 smoker with paper makes cigarette
2018/02/04 19:28:24 smoker with paper smokes
2018/02/04 19:28:24 agent provides tobacco and paper
2018/02/04 19:28:24 smoker with matches makes cigarette
2018/02/04 19:28:24 smoker with matches smokes
2018/02/04 19:28:24 agent provides paper and a match
2018/02/04 19:28:24 smoker with tobacco makes cigarette
2018/02/04 19:28:24 agent provides tobacco and a match
2018/02/04 19:28:24 smoker with tobacco smokes
2018/02/04 19:28:24 smoker with paper makes cigarette
2018/02/04 19:28:24 smoker with paper smokes
2018/02/04 19:28:24 agent provides tobacco and paper
2018/02/04 19:28:24 smoker with matches makes cigarette
2018/02/04 19:28:24 smoker with matches smokes
----

## watch.go

This is a non-semaphore version of the basic smokers problem implemented with
Go idioms.  While it's an attempt to implement the spirit of the stated
problem, it's a rather large departure from book solution.

The stated problem is one where people observe things, perhaps with their
eyes.  Further we have multiple people observing a common event.  This is a
good application for the Go channel-close pattern to have one goroutine (the
agent, or dealer) broadcast an event (representing dealing of a single item)
to multiple goroutines (the smokers) by closing a channel.

A program could be written where closing a specific channel would represent
dealing two items, but the provided agent code signals separate semaphores for
single items.  In that spirit, this program uses a channel to represent a
single item, and represents the event of the dealer placing the item by closing
the channel.

It uses one more channel to represent the event of a smoker taking the items on
the table.  In this case, the goroutine for the smoker that takes the items
closes the channel.  In this case the other smokers and the dealer as well
"observe" the event by monitoring the channel.

The simulation runs for a number of "rounds" in which the dealer deals two
items and one of the smokers takes the items.  Code in main() that might be
considered simulation initialization runs in each round to create the four
channels and start the smoker goroutines.  Code in main() that should then be
considered dealer actions makes a random 1 of 3 choice to deal two items by
closing the corresponding two channels.

Smoker code uses a select statement to watch on three channels:  two
representing an observation that an item the smoker wants has been placed on
the table, and one representing an observation that another smoker has taken
the items on the table.  If the smoker sees both item events he is watching
for, he "takes" them by closing the take channel, smoking, tallying the round
as done, and then the goroutine ends.  If the smoker sees someone else has
taken the items, the goroutine simply ends.

Back in the dealer (main) goroutine, code also watches for the "take" event as
the signal to start the next round.

The "round" WaitGroup ensures that the smokers have all completed smoking
before ending the simulation by allowing the program to terminate.

----
$ go run -race watch.go
2018/02/05 17:42:24 dealer puts match and paper
2018/02/05 17:42:24 smoker with tobacco smokes
2018/02/05 17:42:24 dealer puts paper and tobacco
2018/02/05 17:42:24 smoker with match smokes
2018/02/05 17:42:24 dealer puts match and paper
2018/02/05 17:42:24 smoker with tobacco smokes
2018/02/05 17:42:24 dealer puts match and paper
2018/02/05 17:42:24 smoker with tobacco smokes
2018/02/05 17:42:24 dealer puts tobacco and match
2018/02/05 17:42:24 smoker with paper smokes
2018/02/05 17:42:24 dealer puts paper and tobacco
2018/02/05 17:42:24 smoker with match smokes
2018/02/05 17:42:24 dealer puts tobacco and match
2018/02/05 17:42:24 smoker with paper smokes
2018/02/05 17:42:24 dealer puts match and paper
2018/02/05 17:42:24 smoker with tobacco smokes
2018/02/05 17:42:24 dealer puts tobacco and match
2018/02/05 17:42:24 smoker with paper smokes
2018/02/05 17:42:24 dealer puts paper and tobacco
2018/02/05 17:42:24 smoker with match smokes
----

## generalized.go

Again, a pretty literal implementation of the book solution.  It's interesting
to see that it's a few lines shorter than chanSem.go, in spite of the
suggestion that it's a more difficult problem

----
$ go run -race generalized.go
2018/02/05 17:48:06 agent provides tobacco and paper
2018/02/05 17:48:06 agent provides tobacco and paper
2018/02/05 17:48:06 agent provides paper and a match
2018/02/05 17:48:06 agent provides paper and a match
2018/02/05 17:48:06 agent provides tobacco and a match
2018/02/05 17:48:06 agent provides tobacco and paper
2018/02/05 17:48:06 agent provides tobacco and a match
2018/02/05 17:48:06 smoker with matches makes cigarette
2018/02/05 17:48:06 smoker with matches smokes
2018/02/05 17:48:06 agent provides tobacco and a match
2018/02/05 17:48:06 smoker with paper makes cigarette
2018/02/05 17:48:06 smoker with tobacco makes cigarette
2018/02/05 17:48:06 smoker with tobacco smokes
2018/02/05 17:48:06 smoker with paper smokes
2018/02/05 17:48:06 smoker with paper makes cigarette
2018/02/05 17:48:06 smoker with paper smokes
2018/02/05 17:48:06 smoker with matches makes cigarette
2018/02/05 17:48:06 smoker with matches smokes
2018/02/05 17:48:06 agent provides paper and a match
2018/02/05 17:48:06 smoker with matches makes cigarette
2018/02/05 17:48:06 smoker with matches smokes
2018/02/05 17:48:06 smoker with matches makes cigarette
2018/02/05 17:48:06 smoker with matches smokes
2018/02/05 17:48:06 agent provides tobacco and paper
2018/02/05 17:48:06 smoker with tobacco makes cigarette
2018/02/05 17:48:06 smoker with paper makes cigarette
2018/02/05 17:48:06 smoker with paper smokes
2018/02/05 17:48:06 smoker with tobacco smokes
2018/02/05 17:48:06 smoker with tobacco makes cigarette
2018/02/05 17:48:06 smoker with tobacco smokes
----

## table.go

Non-semaphore version of the generalized problem, again very different.

I follow the observation metaphor again, but a little differently.  It would
be possible to use the channel-close technique again to signal "something has
changed" but then it would take a bunch of mutex locking (probably best done
with a RWMutex) for each of the smokers to look and see just what had changed.
Instead, this program broadcasts the changes directly to the smokers.  This
requires a separate "line of sight" channel for each smoker but has this
advantage of easing the mutex traffic.

The simulation starts by creating a "line of sight" channel for each of the
three smokers (variable "rc") and starting the smoker goroutines.  It then
iterates for a number of rounds in which the dealer deals a single item.
I saw no reason he needs to deal two at a time so I had him deal one at a
time but play twice as many rounds.

In what should be considered the dealer code then, the dealer makes a random
1 of 3 choice for which item to deal, then _acquires the mutex lock for the
table_.  He modifies the item count on the table, then releases the lock.

In what can be considered simulation code, a snapshot (variable tr) is taken
of the new table configuration while still inside the mutex.  This snapshot
is then broadcast to each of the smokers on their "line of sight" goroutines.

Smoker goroutines in this program run once for the simulation; they are not
restarted each round as in watch.go.  A little bit of smoker initialization
code is to take the item they have and set some variables for the items they
want.  This allows the same smoker code to serve for all three smokers.

They then loop over their personal "line of sight" channel (goroutine parameter
"report").  In each iteration they evaluate the latest report for the items
they want.  If they see what they want, then it is their turn to acquire the
lock on the table.  Once they have the lock, they must look again to make sure
another smoker didn't snatch away what they need.  If their items are still
present, they "take" the items by updating the counts on the table, unlock the
mutex and then smoke.

After the dealer has dealt all rounds, code in main closes each of the "line of
sight" channels.  We might imagine this signal to represent the dealer leaving
the table, an observation that is sent to each smoker by the channel close
operation.  The smoker goroutines are looping on this channel.  The loop
detects the channel close after it has looped over all previously sent data
and then terminates.  When the smoker loops terminate, the goroutine signals it
is done with the WaitGroup, then the goroutine terminates.  The main goroutine
code waits for all smoker goroutines to report done, thus ensuring all output
is complete before finally terminating the simulation.

----
$ go run -race table.go
2018/02/05 18:41:47 dealer puts matches (p t m: 0 0 1)
2018/02/05 18:41:47 dealer puts paper (p t m: 1 0 1)
2018/02/05 18:41:47 smoker with tobacco smokes.  (p t m: 0 0 0)
2018/02/05 18:41:47 dealer puts matches (p t m: 0 0 1)
2018/02/05 18:41:47 dealer puts matches (p t m: 0 0 2)
2018/02/05 18:41:47 dealer puts tobacco (p t m: 0 1 2)
2018/02/05 18:41:47 dealer puts paper (p t m: 1 1 2)
2018/02/05 18:41:47 smoker with paper smokes.  (p t m: 1 0 1)
2018/02/05 18:41:47 dealer puts tobacco (p t m: 1 1 1)
2018/02/05 18:41:47 smoker with paper smokes.  (p t m: 1 0 0)
2018/02/05 18:41:47 dealer puts matches (p t m: 1 0 1)
2018/02/05 18:41:47 smoker with tobacco smokes.  (p t m: 0 0 0)
2018/02/05 18:41:47 dealer puts tobacco (p t m: 0 1 0)
2018/02/05 18:41:47 dealer puts paper (p t m: 1 1 0)
2018/02/05 18:41:47 dealer puts matches (p t m: 1 1 1)
2018/02/05 18:41:47 smoker with tobacco smokes.  (p t m: 0 1 0)
2018/02/05 18:41:47 dealer puts tobacco (p t m: 0 2 0)
2018/02/05 18:41:47 dealer puts paper (p t m: 1 2 0)
2018/02/05 18:41:47 dealer puts matches (p t m: 1 2 1)
2018/02/05 18:41:47 smoker with paper smokes.  (p t m: 1 1 0)
2018/02/05 18:41:47 smoker with matches smokes.  (p t m: 0 0 0)
2018/02/05 18:41:47 dealer puts tobacco (p t m: 0 1 0)
2018/02/05 18:41:47 dealer puts matches (p t m: 0 1 1)
2018/02/05 18:41:47 smoker with paper smokes.  (p t m: 0 0 0)
2018/02/05 18:41:47 dealer puts paper (p t m: 1 0 0)
2018/02/05 18:41:47 dealer puts matches (p t m: 1 0 1)
2018/02/05 18:41:47 smoker with tobacco smokes.  (p t m: 0 0 0)
2018/02/05 18:41:47 dealer puts matches (p t m: 0 0 1)
2018/02/05 18:41:47 dealer puts matches (p t m: 0 0 2)
----
