# 4.1 Producer-consumer

## book.go

In my semaphor-based implementation, I started with a cut and paste from the
book solution and tried to modify it minimally.  In my interpretation, I start
a producer goroutine for each event.  A producer goroutine gets a single event, buffers it, and then terminates.  For the consumer code though, I added a loop.
One or more consumer goroutines can be started.  They run continuously and all
consume from the single buffer.  The print statements are just to make a nice
simulation.

----
$ go run book.go
2018/01/28 22:47:10 producer 6 produces event 1
2018/01/28 22:47:10   consumer 2 gets event 1
2018/01/28 22:47:10     processed: event 1
2018/01/28 22:47:10 producer 3 produces event 2
2018/01/28 22:47:10 producer 5 produces event 6
2018/01/28 22:47:10   consumer 1 gets event 2
2018/01/28 22:47:10     processed: event 2
2018/01/28 22:47:10 producer 4 produces event 5
2018/01/28 22:47:10   consumer 1 gets event 5
2018/01/28 22:47:10   consumer 2 gets event 6
2018/01/28 22:47:10     processed: event 6
2018/01/28 22:47:10 producer 1 produces event 3
2018/01/28 22:47:10   consumer 2 gets event 3
2018/01/28 22:47:10     processed: event 3
2018/01/28 22:47:10 producer 2 produces event 4
2018/01/28 22:47:10   consumer 2 gets event 4
2018/01/28 22:47:10     processed: event 4
2018/01/28 22:47:10     processed: event 5
----

## chan.go

The items semaphore and mutex protected buffer implementation get replaced
with a simple unbuffered channel.  This works as long as we stick with the
plan of running a producer goroutine for each event.  The producers can
block on the channel send and get queued up by the channel.  This internal
queue is effectively the buffer.

----
$ go run chan.go
2018/01/28 22:52:21 producer 6 produces event 1
2018/01/28 22:52:21   consumer 2 gets event 1
2018/01/28 22:52:21     processed: event 1
2018/01/28 22:52:21 producer 4 produces event 3
2018/01/28 22:52:21 producer 2 produces event 2
2018/01/28 22:52:21   consumer 2 gets event 2
2018/01/28 22:52:21     processed: event 2
2018/01/28 22:52:21 producer 3 produces event 4
2018/01/28 22:52:21   consumer 2 gets event 4
2018/01/28 22:52:21     processed: event 4
2018/01/28 22:52:21 producer 5 produces event 6
2018/01/28 22:52:21   consumer 2 gets event 6
2018/01/28 22:52:21     processed: event 6
2018/01/28 22:52:21 producer 1 produces event 5
2018/01/28 22:52:21   consumer 1 gets event 3
2018/01/28 22:52:21   consumer 2 gets event 5
2018/01/28 22:52:21     processed: event 5
2018/01/28 22:52:21     processed: event 3
----

# 4.1.4 Producer-consumer with a finite buffer

## finiteSem.go

This book solution works as advertised, with the sliding slice buffer replaced
by ring buffer:

----
$ go run finiteSem.go
2018/01/29 00:07:49 producer 6 produces event 2
2018/01/29 00:07:49 producer 3 produces event 3
2018/01/29 00:07:49 producer 2 produces event 5
2018/01/29 00:07:49   consumer 1 gets event 3
2018/01/29 00:07:49     processed: event 3
2018/01/29 00:07:49   consumer 1 gets event 5
2018/01/29 00:07:49     processed: event 5
2018/01/29 00:07:49 producer 1 produces event 1
2018/01/29 00:07:49   consumer 1 gets event 1
2018/01/29 00:07:49     processed: event 1
2018/01/29 00:07:49 producer 5 produces event 4
2018/01/29 00:07:49   consumer 1 gets event 4
2018/01/29 00:07:49     processed: event 4
2018/01/29 00:07:49 producer 4 produces event 6
2018/01/29 00:07:49   consumer 1 gets event 6
2018/01/29 00:07:49     processed: event 6
2018/01/29 00:07:49   consumer 2 gets event 2
2018/01/29 00:07:49     processed: event 2
----

## finite.go

For the finite buffer we use a Go buffered channel.  The difference from
`chan.go`, the "unbounded" solution is subtle.  In `chan.go` the unbounded part
is that any number of goroutines can be waiting to send.  Here in `finite.go`,
the buffered channel can handle a number of these goroutines immediately and
allow them to terminate.

----
$ go run finite.go
2018/01/29 00:12:24 producer 6 produces event 1
2018/01/29 00:12:24 producer 1 produces event 2
2018/01/29 00:12:24   consumer 2 gets event 2
2018/01/29 00:12:24     processed: event 2
2018/01/29 00:12:24 producer 4 produces event 5
2018/01/29 00:12:24   consumer 2 gets event 5
2018/01/29 00:12:24     processed: event 5
2018/01/29 00:12:24 producer 5 produces event 6
2018/01/29 00:12:24   consumer 2 gets event 6
2018/01/29 00:12:24     processed: event 6
2018/01/29 00:12:24 producer 3 produces event 3
2018/01/29 00:12:24   consumer 2 gets event 3
2018/01/29 00:12:24     processed: event 3
2018/01/29 00:12:24 producer 2 produces event 4
2018/01/29 00:12:24   consumer 2 gets event 4
2018/01/29 00:12:24     processed: event 4
2018/01/29 00:12:24   consumer 1 gets event 1
2018/01/29 00:12:24     processed: event 1
----

----
