# 3.6 Barrier

Quoting from the book,  "Every thread should run the following code:"

.Barrier code
----
rendezvous
critical point
----

It's a little unclear what these two lines are supposed to be.  Are they
referencing some specific already-introduced code implementing rendezvous and
critical point?  Are they function names for functions that might do some
arbitrary application-specific task?  Are they just general concepts?

I'm going to implement them as print statements, just indicating that some
code is being excecuted.

## chanSem.go

This is the literal interpretation.

Output from an example run:

----
$ go run chanSem.go
2018/01/27 13:23:43 gr 0 rendezvous
2018/01/27 13:23:43 gr 3 rendezvous
2018/01/27 13:23:43 gr 2 rendezvous
2018/01/27 13:23:43 gr 1 rendezvous
2018/01/27 13:23:43 gr 4 rendezvous
2018/01/27 13:23:43 gr 0 critical point
2018/01/27 13:23:43 gr 2 critical point
2018/01/27 13:23:43 gr 3 critical point
2018/01/27 13:23:43 gr 1 critical point
2018/01/27 13:23:43 gr 4 critical point
----

All goroutines execute their "rendezvous" code, wait for each other, then
execute their "critical point" code.

This use of words rendezvous and critical point still seems confusing.  How
about instead "before barrier" and "after barrier".

Much more disturbing though is the note in the text,

____
It might seem dangerous to read the value of count outside the mutex. In
this case it is not a problem, but in general it is probably not a good idea.
____

It does seem dangerous.  What does the Go race detector think?

----
$ go run -race chanSem.go
2018/01/30 14:59:15 gr 0 rendezvous
2018/01/30 14:59:15 gr 1 rendezvous
==================
2018/01/30 14:59:15 gr 2 rendezvous
WARNING: DATA RACE
Write at 0x0000005d1140 by goroutine 7:
  main.gr()
      /home/sonia/go/src/github.com/soniakeys/LittleBookOfSemaphores/3-Basic_Synchronization_Patterns/3.6-Barrier/chanSem.go:22 +0x166

Previous read at 0x0000005d1140 by goroutine 6:
  main.gr()
      /home/sonia/go/src/github.com/soniakeys/LittleBookOfSemaphores/3-Basic_Synchronization_Patterns/3.6-Barrier/chanSem.go:24 +0x1c4

Goroutine 7 (running) created at:
2018/01/30 14:59:15 gr 3 rendezvous
  main.main()
      /home/sonia/go/src/github.com/soniakeys/LittleBookOfSemaphores/3-Basic_Synchronization_Patterns/3.6-Barrier/chanSem.go:36 +0xa2

Goroutine 6 (running) created at:
  main.main()
      /home/sonia/go/src/github.com/soniakeys/LittleBookOfSemaphores/3-Basic_Synchronization_Patterns/3.6-Barrier/chanSem.go:36 +0xa2
==================
2018/01/30 14:59:15 gr 4 rendezvous
2018/01/30 14:59:15 gr 0 critical point
2018/01/30 14:59:15 gr 1 critical point
2018/01/30 14:59:15 gr 2 critical point
2018/01/30 14:59:15 gr 3 critical point
2018/01/30 14:59:15 gr 4 critical point
Found 1 data race(s)
exit status 66
----

Why read the value of count outside the mutex?  I don't know.  I tried putting
it inside the mutex and the program seems to work okay and keep the race
detector happy.

## atomic.go

Here's a variant of mine still using the barrier semaphore but using Go's
sync/atomic for the count.  The mutex protected count didn't seem part of the
problem, and also atomic nicely avoids the sketchy racey code where count
is tested outside of the mutex.

## close.go

A version without semaphores.  It's a significant departure from the book
solution, but one I think still captures the idea of a barrier.  Instead of
maintaining a count and relying on one of the goroutines to recognize that it
is last, it uses a WaitGroup to let a supervisory goroutine (main) wait for all
of the worker goroutines to finish their before-barrier work.

Main then uses a Go idiom for broadcasting a signal -- it closes a channel.
Closing a channel in Go causes it to thereafter send a zero value of the
channel type in response to any number of receive requests.  Main creates
this channel and leaves it empty.  Then at the "barrier", workers all block
trying to recieve from the empty channel.  Main waits for the WaitGroup
signalling all workers are at the barrier, then closes the channel.
All workers then succeed at getting a zero value from the channel and
proceed to their after-barrier work.

Note that a couple of contrivences of the book solution are not needed here.
There is no explicit count, just that maintained by the WaitGroup.  One
worker does not have to take up a supervisory role.  And there is no
"turnstile" needed.  The channel close idiom effectively releases all workers
at once.

----
$ go run -race close.go
2018/01/27 14:00:06 gr 0 rendezvous (before barrier)
2018/01/27 14:00:06 gr 3 rendezvous (before barrier)
2018/01/27 14:00:06 gr 1 rendezvous (before barrier)
2018/01/27 14:00:06 gr 2 rendezvous (before barrier)
2018/01/27 14:00:06 gr 4 rendezvous (before barrier)
2018/01/27 14:00:06 gr 1 critical point (after barrier)
2018/01/27 14:00:06 gr 4 critical point (after barrier)
2018/01/27 14:00:06 gr 0 critical point (after barrier)
2018/01/27 14:00:06 gr 2 critical point (after barrier)
2018/01/27 14:00:06 gr 3 critical point (after barrier)
----
